spring:
  config:
    activate:
      on-profile: local
    import: application-secret.yml

logging:
  level:
    click.metroeye.api: debug
    org.springframework: info
    o.r2dbc.mysql: debug
    io.r2dbc.pool: debug