spring:
  config:
    activate:
      on-profile: dev
  r2dbc:
    master:
      url: r2dbc:mysql://${DB_DEV_MASTER_HOST}:${DB_DEV_MASTER_PORT}/${DB_DEV_NAME}?serverTimezone=Asia/Seoul
      username: ${DB_DEV_MASTER_USERNAME}
      password: ${DB_DEV_MASTER_PASSWORD}
      pool:
        enabled: true
        max-acquire-time: 60s
        max-life-time: 60m
        max-idle-time: 30m
        validation-query: SELECT 1
    slave:
      url: r2dbc:mysql://${DB_DEV_MASTER_HOST}:${DB_DEV_MASTER_PORT}/${DB_DEV_NAME}?serverTimezone=Asia/Seoul
      username: ${DB_DEV_MASTER_USERNAME}
      password: ${DB_DEV_MASTER_PASSWORD}
      pool:
        enabled: true
        max-acquire-time: 60s
        max-life-time: 60m
        max-idle-time: 30m
        validation-query: SELECT 1

jwt:
  secret: ${JWT_SECRET}

external-api:
  seoul-public-data:
    subway:
      api-key: ${SEOUL_SUBWAY_API_KEY}

app:
  min-version: 1.0.0
  maintenance: false

logging:
  level:
    click.metroeye.api: info
    org.springframework: info