spring:
  config:
    activate:
      on-profile: local
    import: application-secret.yml

logging:
  level:
    click.metroeye.api: debug
    org.springframework: info
#    org.springframework.r2dbc: debug
#    io.r2dbc.pool: debug
#    io.asyncer.r2dbc.mysql: debug