spring:
  config:
    activate:
      on-profile: dev

external-api:
  seoul-public-data:
    subway:
      api-key: ${SEOUL_SUBWAY_API_KEY}

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    use-root-path: true
    tags-sorter: alpha
    operations-sorter: method
    default-model-expand-depth: 2

logging:
  level:
    click.metroeye.api: info
    org.springframework: info